--- #YAML:1.0
name:                Algorithm-Munkres
version:             0.08
abstract:            Munkres.pm
license:             ~
author:              
    - Anagha Kulkarni <kulka020@d.umn.edu>, Ted Pedersen <tpederse@d.umn.edu>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
